<?php

return [
    'name' => 'plugins/real-estate::settings.email.title',
    'description' => 'plugins/real-estate::settings.email.description',
    'templates' => [
        'notice' => [
            'title' => 'New consult',
            'description' => 'Send to the agent email / admin email when someone contact via consult form',
            'subject' => 'New consult',
            'can_off' => true,
            'variables' => [
                'consult_name' => 'Name',
                'consult_phone' => 'Phone',
                'consult_email' => 'Email',
                'consult_content' => 'Content',
                'consult_link' => 'Link',
                'consult_subject' => 'Subject',
                'consult_ip_address' => 'IP address',
                'consult_custom_fields' => 'Custom fields',
            ],
        ],
        'vacation_rental_booking_inquiry' => [
            'title' => 'Vacation Rental Booking Inquiry',
            'description' => 'Send to the property owner / admin email when someone submits a vacation rental booking inquiry',
            'subject' => 'New Vacation Rental Booking Inquiry',
            'can_off' => true,
            'variables' => [
                'consult_name' => 'Guest Name',
                'consult_phone' => 'Phone',
                'consult_email' => 'Email',
                'consult_content' => 'Message',
                'consult_link' => 'Admin Link',
                'consult_subject' => 'Subject',
                'consult_ip_address' => 'IP address',
                'consult_custom_fields' => 'Custom fields',
                'property_name' => 'Property Name',
                'check_in_date' => 'Check-in Date',
                'check_out_date' => 'Check-out Date',
                'guests_count' => 'Number of Guests',
            ],
        ],
        'vacation_rental_booking_confirmed' => [
            'title' => 'Vacation rental booking confirmed',
            'description' => 'Send to the property owner when a vacation rental booking is confirmed',
            'subject' => 'New Booking Confirmed - {{ property_name }} #{{ booking_number }}',
            'can_off' => true,
            'variables' => [
                'booking_number' => 'Booking Number',
                'property_name' => 'Property Name',
                'property_link' => 'Property Link',
                'guest_name' => 'Guest Name',
                'guest_email' => 'Guest Email',
                'guest_phone' => 'Guest Phone',
                'check_in_date' => 'Check-in Date',
                'check_out_date' => 'Check-out Date',
                'guests_count' => 'Number of Guests',
                'total_amount' => 'Total Amount',
                'payment_status' => 'Payment Status',
                'special_requests' => 'Special Requests',
                'booking_link' => 'Booking Details Link',
            ],
        ],
        'new-pending-property' => [
            'title' => 'New pending property',
            'description' => 'Send email to admin when a new property created',
            'subject' => 'New pending property by {{ post_author }} waiting for approve',
            'can_off' => true,
            'enabled' => false,
            'variables' => [
                'post_author' => 'Post Author',
                'post_name' => 'Post Name',
                'post_url' => 'Post URL',
            ],
        ],
        'account-registered' => [
            'title' => 'Account registered',
            'description' => 'Send a notification to admin when a new account registered',
            'subject' => 'New account registered on {{ site_title }}',
            'can_off' => true,
            'enabled' => false,
            'variables' => [
                'account_name' => 'Account name',
                'account_email' => 'Account email',
            ],
        ],
        'confirm-email' => [
            'title' => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject' => 'Confirm Email Notification',
            'can_off' => false,
            'variables' => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'password-reminder' => [
            'title' => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject' => 'Reset Password',
            'can_off' => false,
            'variables' => [
                'reset_link' => 'Reset password link',
            ],
        ],
        'payment-receipt' => [
            'title' => 'Payment receipt',
            'description' => 'Send a notification to user when they buy credits',
            'subject' => 'Payment receipt for package {{ package_name }} on {{ site_title }}',
            'can_off' => true,
            'enabled' => false,
            'variables' => [
                'account_name' => 'Account name',
                'account_email' => 'Account email',
                'package_name' => 'Name of package',
                'package_price' => 'Price',
                'package_percent_discount' => 'Discount',
                'package_number_of_listings' => 'Number of package listings',
            ],
        ],
        'free-credit-claimed' => [
            'title' => 'Free credit claimed',
            'description' => 'Send a notification to admin when free credit is claimed',
            'subject' => '{{ account_name }} has claimed free credit on {{ site_title }}',
            'can_off' => true,
            'enabled' => false,
            'variables' => [
                'account_name' => 'Account name',
                'account_email' => 'Account email',
            ],
        ],
        'payment-received' => [
            'title' => 'Payment received',
            'description' => 'Send a notification to admin when someone buy credits',
            'subject' => 'Payment received from {{ account_name }} on {{ site_title }}',
            'can_off' => true,
            'enabled' => false,
            'variables' => [
                'account_name' => 'Account name',
                'account_email' => 'Account email',
                'package_name' => 'Name of package',
                'package_price' => 'Price',
                'package_percent_discount' => 'Discount',
                'package_number_of_listings' => 'Number of package listings',
            ],
        ],
        'account-approved' => [
            'title' => 'Account approved',
            'description' => 'Send an email notification to the user when their account is approved',
            'subject' => 'Your account on {{ site_title }} has been approved',
            'can_off' => true,
            'variables' => [
                'account_name' => 'Account name',
                'account_email' => 'Account email',
            ],
        ],
        'account-rejected' => [
            'title' => 'Account rejected',
            'description' => 'Send an email notification to the user when their account is rejected',
            'subject' => 'Your account on {{ site_title }} has been rejected',
            'can_off' => true,
            'variables' => [
                'account_name' => 'Account name',
                'account_email' => 'Account email',
                'rejection_reason' => 'Reason for rejection',
            ],
        ],
        'property-approved' => [
            'title' => 'Property approved',
            'description' => 'Send an email notification to the agent when their property is approved',
            'subject' => 'Your property on {{ site_title }} has been approved',
            'can_off' => true,
            'variables' => [
                'author_name' => 'Author name',
                'property_name' => 'Property name',
                'property_link' => 'Property link',
            ],
        ],
        'property-rejected' => [
            'title' => 'Property rejected',
            'description' => 'Send an email notification to the agent when their property is rejected',
            'subject' => 'Your property on {{ site_title }} has been rejected',
            'can_off' => true,
            'variables' => [
                'author_name' => 'Author name',
                'property_name' => 'Property name',
                'property_link' => 'Property link',
                'reason' => 'Reason for rejection',
            ],
        ],

        'booking-processing-customer' => [
            'title' => 'Vacation Rental Booking Processing (Customer)',
            'description' => 'Send to customer immediately when booking is submitted (before payment confirmation)',
            'subject' => 'Processing Your Booking Request - {{ property_name }}',
            'can_off' => true,
            'variables' => [
                'customer_name' => 'Customer Name',
                'property_name' => 'Property Name',
                'property_link' => 'Property Link',
                'check_in_date' => 'Check-in Date',
                'check_out_date' => 'Check-out Date',
                'guests_count' => 'Number of Guests',
                'total_amount' => 'Total Amount',
                'booking_reference' => 'Booking Reference',
                'estimated_confirmation_time' => 'Estimated Confirmation Time',
            ],
        ],
        'vacation-rental-booking-confirmation' => [
            'title' => 'Vacation Rental Booking Confirmation',
            'description' => 'Send booking confirmation email to customer when vacation rental booking is completed',
            'subject' => 'Booking Confirmation #{{ booking_number }} - {{ property_name }}',
            'can_off' => true,
            'variables' => [
                'customer_name' => 'Customer Name',
                'customer_email' => 'Customer Email',
                'booking_number' => 'Booking Number',
                'property_name' => 'Property Name',
                'property_address' => 'Property Address',
                'check_in_date' => 'Check-in Date',
                'check_out_date' => 'Check-out Date',
                'guests_count' => 'Number of Guests',
                'total_amount' => 'Total Amount',
                'booking_details_link' => 'Booking Details Link',
                'property_link' => 'Property Link',
                'booking_status' => 'Booking Status',
                'special_requests' => 'Special Requests',
            ],
        ],
    ],
];
